- name: Identify and print specific interface
  hosts: server
  vars:
    target_mac: "52:54:00:01:fa:0a"
  tasks:
    - name: Find the_interface for target_mac
      set_fact:
        the_interface: "{{ item }}"
      when:
        - ansible_facts[item]['macaddress'] is defined
        - ansible_facts[item]['macaddress'] == target_mac
      loop: "{{ ansible_facts['interfaces'] }}"
    - name: Display the_interface
      debug:
        var: the_interface
